from service.db.loader import Loader


class FakeLoader(Loader):

    def download_file(self, url):
        return [
        {
            "name__title": "mrs",
            "name__first": "Nina",
            "name__last": "Rodrigues",
            "gender": "female",
            "location__street": "Colônia Ana Beatriz Dias, 6",
            "location__postcode": "84140-163",
            "location__city": "Aragão",
            "location__state": "MG",
            "location__coordinates__latitude": 55.685243,
            "location__coordinates__longitude": 79.047509,
            "phone": "81 3881 6116",
            "picture__large": "https://www.pires.net/NinaRodrigues/large.png",
            "picture__medium": "https://www.pires.net/NinaRodrigues/medium.jpg",
            "picture__thumbnail": "https://www.pires.net/NinaRodrigues/thumbnail.gif"
        },
        {
            "name__title": "miss",
            "name__first": "Luiza",
            "name__last": "Oliveira",
            "gender": "female",
            "location__street": "Passarela Benjamin Santos, 1",
            "location__postcode": "69757834",
            "location__city": "Lima",
            "location__state": "RO",
            "location__coordinates__latitude": -48.52416057042378,
            "location__coordinates__longitude": -21.76564042586542,
            "phone": "(021) 1115-1489",
            "picture__large": "http://moura.br/LuizaOliveira/large.png",
            "picture__medium": "http://moura.br/LuizaOliveira/medium.jpg",
            "picture__thumbnail": "http://moura.br/LuizaOliveira/thumbnail.gif"
        },
        {
            "name__title": "mrs",
            "name__first": "Laura",
            "name__last": "Jesus",
            "gender": "female",
            "location__street": "Praça Alana Fogaça, 5",
            "location__postcode": "55207-378",
            "location__city": "Aragão",
            "location__state": "BA",
            "location__coordinates__latitude": 80.9465445,
            "location__coordinates__longitude": -5.891820,
            "phone": "496-6190",
            "picture__large": "https://www.silveira.org/LauraJesus/large.png",
            "picture__medium": "https://www.silveira.org/LauraJesus/medium.jpg",
            "picture__thumbnail": "https://www.silveira.org/LauraJesus/thumbnail.gif"
        },
        {
            "name__title": "mr",
            "name__first": "Bruno",
            "name__last": "Cunha",
            "gender": "male",
            "location__street": "Largo de Castro, 7",
            "location__postcode": "86270-952",
            "location__city": "Ramos",
            "location__state": "PB",
            "location__coordinates__latitude": -48.52416057042378,
            "location__coordinates__longitude": -21.76564042586542,
            "phone": "591-2276",
            "picture__large": "http://nascimento.com/BrunoCunha/large.png",
            "picture__medium": "http://nascimento.com/BrunoCunha/medium.jpg",
            "picture__thumbnail": "http://nascimento.com/BrunoCunha/thumbnail.gif"
        },
        {
            "name__title": "miss",
            "name__first": "Valentina",
            "name__last": "Melo",
            "gender": "female",
            "location__street": "Passarela Fernanda Silveira, 16",
            "location__postcode": "09674-234",
            "location__city": "Caldeira",
            "location__state": "PB",
            "location__coordinates__latitude": 6.6885685,
            "location__coordinates__longitude": 74.117509,
            "phone": "61 5199-6617",
            "picture__large": "https://www.ramos.net/ValentinaMelo/large.png",
            "picture__medium": "https://www.ramos.net/ValentinaMelo/medium.jpg",
            "picture__thumbnail": "https://www.ramos.net/ValentinaMelo/thumbnail.gif"
        },
        {
            "name__title": "mr",
            "name__first": "Alexandre",
            "name__last": "Costela",
            "gender": "male",
            "location__street": "Loteamento Martins, 14",
            "location__postcode": "97954807",
            "location__city": "Rocha",
            "location__state": "SC",
            "location__coordinates__latitude": -48.52416057042378,
            "location__coordinates__longitude": -21.76564042586542,
            "phone": "022-3526",
            "picture__large": "https://www.mendes.com/AlexandreCostela/large.png",
            "picture__medium": "https://www.mendes.com/AlexandreCostela/medium.jpg",
            "picture__thumbnail": "https://www.mendes.com/AlexandreCostela/thumbnail.gif"
        },
        {
            "name__title": "mr",
            "name__first": "João Lucas",
            "name__last": "Melo",
            "gender": "male",
            "location__street": "Setor Novaes, 7",
            "location__postcode": "73240892",
            "location__city": "Viana",
            "location__state": "SC",
            "location__coordinates__latitude": -25.676959,
            "location__coordinates__longitude": 51.796022,
            "phone": "(021) 3718 3372",
            "picture__large": "https://www.silveira.net/João LucasMelo/large.png",
            "picture__medium": "https://www.silveira.net/João LucasMelo/medium.jpg",
            "picture__thumbnail": "https://www.silveira.net/João LucasMelo/thumbnail.gif"
        },
        {
            "name__title": "mrs",
            "name__first": "Luna",
            "name__last": "da Mata",
            "gender": "female",
            "location__street": "Trevo Ribeiro, 7",
            "location__postcode": "85339075",
            "location__city": "Melo",
            "location__state": "PI",
            "location__coordinates__latitude": -50.52549001027845,
            "location__coordinates__longitude": -29.82823885923113,
            "phone": "51 4303 2690",
            "picture__large": "http://ribeiro.com/Lunada Mata/large.png",
            "picture__medium": "http://ribeiro.com/Lunada Mata/medium.jpg",
            "picture__thumbnail": "http://ribeiro.com/Lunada Mata/thumbnail.gif"
        },
        {
            "name__title": "miss",
            "name__first": "Sofia",
            "name__last": "Barbosa",
            "gender": "female",
            "location__street": "Sítio Agatha Martins, 80",
            "location__postcode": "27319821",
            "location__city": "Santos",
            "location__state": "AP",
            "location__coordinates__latitude": 40.525871,
            "location__coordinates__longitude": -48.581287,
            "phone": "781 9707",
            "picture__large": "https://dias.com/SofiaBarbosa/large.png",
            "picture__medium": "https://dias.com/SofiaBarbosa/medium.jpg",
            "picture__thumbnail": "https://dias.com/SofiaBarbosa/thumbnail.gif"
        },
        {
            "name__title": "mrs",
            "name__first": "Clara",
            "name__last": "Almeida",
            "gender": "female",
            "location__street": "Chácara Oliveira, 88",
            "location__postcode": "53568-852",
            "location__city": "da",
            "location__state": "CE",
            "location__coordinates__latitude": -48.52416057042378,
            "location__coordinates__longitude": -21.76564042586542,
            "phone": "(031) 0024-0426",
            "picture__large": "https://www.teixeira.org/ClaraAlmeida/large.png",
            "picture__medium": "https://www.teixeira.org/ClaraAlmeida/medium.jpg",
            "picture__thumbnail": "https://www.teixeira.org/ClaraAlmeida/thumbnail.gif"
        },
        {
            "name__title": "miss",
            "name__first": "Alexia",
            "name__last": "Rezende",
            "gender": "female",
            "location__street": "Núcleo Caldeira, 991",
            "location__postcode": "21611-338",
            "location__city": "da",
            "location__state": "PI",
            "location__coordinates__latitude": 55.6257365,
            "location__coordinates__longitude": 43.853465,
            "phone": "104-7534",
            "picture__large": "https://pinto.com/AlexiaRezende/large.png",
            "picture__medium": "https://pinto.com/AlexiaRezende/medium.jpg",
            "picture__thumbnail": "https://pinto.com/AlexiaRezende/thumbnail.gif"
        },
        {
            "name__title": "mr",
            "name__first": "Henrique",
            "name__last": "Monteiro",
            "gender": "male",
            "location__street": "Distrito de Rezende, 21",
            "location__postcode": "56904855",
            "location__city": "Monteiro",
            "location__state": "PR",
            "location__coordinates__latitude": -48.52416057042378,
            "location__coordinates__longitude": -21.76564042586542,
            "phone": "(084) 6668-3948",
            "picture__large": "https://melo.com/HenriqueMonteiro/large.png",
            "picture__medium": "https://melo.com/HenriqueMonteiro/medium.jpg",
            "picture__thumbnail": "https://melo.com/HenriqueMonteiro/thumbnail.gif"
        },
        {
            "name__title": "mr",
            "name__first": "Diogo",
            "name__last": "Nascimento",
            "gender": "male",
            "location__street": "Largo Pinto, 80",
            "location__postcode": "21846-931",
            "location__city": "Campos",
            "location__state": "MS",
            "location__coordinates__latitude": 73.5465885,
            "location__coordinates__longitude": -44.158214,
            "phone": ") 9610 8289",
            "picture__large": "http://da.br/DiogoNascimento/large.png",
            "picture__medium": "http://da.br/DiogoNascimento/medium.jpg",
            "picture__thumbnail": "http://da.br/DiogoNascimento/thumbnail.gif"
        },
        {
            "name__title": "miss",
            "name__first": "Brenda",
            "name__last": "Silveira",
            "gender": "female",
            "location__street": "Núcleo Fernandes, 1",
            "location__postcode": "95702009",
            "location__city": "Ferreira",
            "location__state": "PA",
            "location__coordinates__latitude": -50.52549001027845,
            "location__coordinates__longitude": -29.82823885923113,
            "phone": "(061) 0827-6523",
            "picture__large": "http://vieira.br/BrendaSilveira/large.png",
            "picture__medium": "http://vieira.br/BrendaSilveira/medium.jpg",
            "picture__thumbnail": "http://vieira.br/BrendaSilveira/thumbnail.gif"
        },
        {
            "name__title": "mr",
            "name__first": "Theo",
            "name__last": "Pereira",
            "gender": "male",
            "location__street": "Aeroporto Carvalho, 6",
            "location__postcode": "24127041",
            "location__city": "da",
            "location__state": "RS",
            "location__coordinates__latitude": -35.2491305,
            "location__coordinates__longitude": -134.100979,
            "phone": "464 8115",
            "picture__large": "https://www.carvalho.com/TheoPereira/large.png",
            "picture__medium": "https://www.carvalho.com/TheoPereira/medium.jpg",
            "picture__thumbnail": "https://www.carvalho.com/TheoPereira/thumbnail.gif"
        },
        {
            "name__title": "mr",
            "name__first": "Ryan",
            "name__last": "Lima",
            "gender": "male",
            "location__street": "Estação de Gonçalves, 41",
            "location__postcode": "58458-470",
            "location__city": "Campos",
            "location__state": "AM",
            "location__coordinates__latitude": -48.52416057042378,
            "location__coordinates__longitude": -21.76564042586542,
            "phone": "(071) 1839 0283",
            "picture__large": "https://www.martins.com/RyanLima/large.png",
            "picture__medium": "https://www.martins.com/RyanLima/medium.jpg",
            "picture__thumbnail": "https://www.martins.com/RyanLima/thumbnail.gif"
        },
        {
            "name__title": "mr",
            "name__first": "Bruno",
            "name__last": "Carvalho",
            "gender": "male",
            "location__street": "Travessa de Teixeira, 524",
            "location__postcode": "66729-372",
            "location__city": "Cavalcanti",
            "location__state": "MA",
            "location__coordinates__latitude": 44.891664,
            "location__coordinates__longitude": 94.137337,
            "phone": "71 9616-3492",
            "picture__large": "https://www.castro.net/BrunoCarvalho/large.png",
            "picture__medium": "https://www.castro.net/BrunoCarvalho/medium.jpg",
            "picture__thumbnail": "https://www.castro.net/BrunoCarvalho/thumbnail.gif"
        },
        {
            "name__title": "mr",
            "name__first": "Enrico",
            "name__last": "da Mata",
            "gender": "male",
            "location__street": "Trevo Luiz Henrique Caldeira, 93",
            "location__postcode": "86336-624",
            "location__city": "Caldeira",
            "location__state": "AC",
            "location__coordinates__latitude": -48.52416057042378,
            "location__coordinates__longitude": -21.76564042586542,
            "phone": "(081) 6372 6628",
            "picture__large": "http://fogaca.net/Enricoda Mata/large.png",
            "picture__medium": "http://fogaca.net/Enricoda Mata/medium.jpg",
            "picture__thumbnail": "http://fogaca.net/Enricoda Mata/thumbnail.gif"
        },
        {
            "name__title": "mrs",
            "name__first": "Sophie",
            "name__last": "da Cunha",
            "gender": "female",
            "location__street": "Estação de Cavalcanti, 2",
            "location__postcode": "05552643",
            "location__city": "Fogaça",
            "location__state": "RS",
            "location__coordinates__latitude": -68.4389295,
            "location__coordinates__longitude": -24.227960,
            "phone": "84 4286-0944",
            "picture__large": "http://www.silva.br/Sophieda Cunha/large.png",
            "picture__medium": "http://www.silva.br/Sophieda Cunha/medium.jpg",
            "picture__thumbnail": "http://www.silva.br/Sophieda Cunha/thumbnail.gif"
        },
        {
            "name__title": "mr",
            "name__first": "Breno",
            "name__last": "Gomes",
            "gender": "male",
            "location__street": "Trevo de Melo, 937",
            "location__postcode": "23535-145",
            "location__city": "Moraes",
            "location__state": "RN",
            "location__coordinates__latitude": -50.52549001027845,
            "location__coordinates__longitude": -29.82823885923113,
            "phone": ") 6426-5306",
            "picture__large": "https://lopes.br/BrenoGomes/large.png",
            "picture__medium": "https://lopes.br/BrenoGomes/medium.jpg",
            "picture__thumbnail": "https://lopes.br/BrenoGomes/thumbnail.gif"
        },
        {
            "name__title": "miss",
            "name__first": "Fernanda",
            "name__last": "Rodrigues",
            "gender": "female",
            "location__street": "Setor Anthony Ribeiro, 17",
            "location__postcode": "01569462",
            "location__city": "da",
            "location__state": "PA",
            "location__coordinates__latitude": -68.173508,
            "location__coordinates__longitude": 140.476187,
            "phone": ") 7373-1409",
            "picture__large": "https://www.melo.com/FernandaRodrigues/large.png",
            "picture__medium": "https://www.melo.com/FernandaRodrigues/medium.jpg",
            "picture__thumbnail": "https://www.melo.com/FernandaRodrigues/thumbnail.gif"
        },
        {
            "name__title": "miss",
            "name__first": "Sofia",
            "name__last": "da Paz",
            "gender": "female",
            "location__street": "Colônia de Nunes",
            "location__postcode": "61563-072",
            "location__city": "da",
            "location__state": "PB",
            "location__coordinates__latitude": -48.52416057042378,
            "location__coordinates__longitude": -21.76564042586542,
            "phone": "(051) 7111 3436",
            "picture__large": "https://da.br/Sofiada Paz/large.png",
            "picture__medium": "https://da.br/Sofiada Paz/medium.jpg",
            "picture__thumbnail": "https://da.br/Sofiada Paz/thumbnail.gif"
        },
        {
            "name__title": "mr",
            "name__first": "Heitor",
            "name__last": "Castro",
            "gender": "male",
            "location__street": "Alameda da Luz, 51",
            "location__postcode": "39785706",
            "location__city": "Monteiro",
            "location__state": "AL",
            "location__coordinates__latitude": 22.147837,
            "location__coordinates__longitude": -78.259163,
            "phone": "(071) 7785-8438",
            "picture__large": "http://www.rodrigues.org/HeitorCastro/large.png",
            "picture__medium": "http://www.rodrigues.org/HeitorCastro/medium.jpg",
            "picture__thumbnail": "http://www.rodrigues.org/HeitorCastro/thumbnail.gif"
        },
        {
            "name__title": "miss",
            "name__first": "Ana Luiza",
            "name__last": "Rezende",
            "gender": "female",
            "location__street": "Avenida Araújo, 50",
            "location__postcode": "64375-093",
            "location__city": "Teixeira",
            "location__state": "ES",
            "location__coordinates__latitude": -48.52416057042378,
            "location__coordinates__longitude": -21.76564042586542,
            "phone": "(061) 9769-2746",
            "picture__large": "https://www.silveira.org/Ana LuizaRezende/large.png",
            "picture__medium": "https://www.silveira.org/Ana LuizaRezende/medium.jpg",
            "picture__thumbnail": "https://www.silveira.org/Ana LuizaRezende/thumbnail.gif"
        },
        {
            "name__title": "mr",
            "name__first": "Pedro Miguel",
            "name__last": "Rocha",
            "gender": "male",
            "location__street": "Rodovia de Silveira, 82",
            "location__postcode": "35305228",
            "location__city": "Moreira",
            "location__state": "PR",
            "location__coordinates__latitude": 20.3761215,
            "location__coordinates__longitude": 177.866095,
            "phone": ") 0500-5310",
            "picture__large": "https://goncalves.br/Pedro MiguelRocha/large.png",
            "picture__medium": "https://goncalves.br/Pedro MiguelRocha/medium.jpg",
            "picture__thumbnail": "https://goncalves.br/Pedro MiguelRocha/thumbnail.gif"
        },
        {
            "name__title": "miss",
            "name__first": "Evelyn",
            "name__last": "Porto",
            "gender": "female",
            "location__street": "Praça de Lopes, 899",
            "location__postcode": "10521697",
            "location__city": "da",
            "location__state": "PA",
            "location__coordinates__latitude": -50.52549001027845,
            "location__coordinates__longitude": -29.82823885923113,
            "phone": "51 3720 1828",
            "picture__large": "http://www.fogaca.com/EvelynPorto/large.png",
            "picture__medium": "http://www.fogaca.com/EvelynPorto/medium.jpg",
            "picture__thumbnail": "http://www.fogaca.com/EvelynPorto/thumbnail.gif"
        },
        {
            "name__title": "mrs",
            "name__first": "Vitória",
            "name__last": "Silva",
            "gender": "female",
            "location__street": "Largo Maria Carvalho, 9",
            "location__postcode": "79391-273",
            "location__city": "Cardoso",
            "location__state": "AP",
            "location__coordinates__latitude": -39.6600735,
            "location__coordinates__longitude": 155.297404,
            "phone": "430 2772",
            "picture__large": "http://www.azevedo.br/VitóriaSilva/large.png",
            "picture__medium": "http://www.azevedo.br/VitóriaSilva/medium.jpg",
            "picture__thumbnail": "http://www.azevedo.br/VitóriaSilva/thumbnail.gif"
        },
        {
            "name__title": "mrs",
            "name__first": "Alexia",
            "name__last": "Moraes",
            "gender": "female",
            "location__street": "Área de Barbosa, 14",
            "location__postcode": "95787-654",
            "location__city": "Duarte",
            "location__state": "GO",
            "location__coordinates__latitude": -48.52416057042378,
            "location__coordinates__longitude": -21.76564042586542,
            "phone": "(051) 4556 5285",
            "picture__large": "http://www.pereira.br/AlexiaMoraes/large.png",
            "picture__medium": "http://www.pereira.br/AlexiaMoraes/medium.jpg",
            "picture__thumbnail": "http://www.pereira.br/AlexiaMoraes/thumbnail.gif"
        },
        {
            "name__title": "mr",
            "name__first": "Bruno",
            "name__last": "Rodrigues",
            "gender": "male",
            "location__street": "Loteamento Lopes, 54",
            "location__postcode": "57633-175",
            "location__city": "Duarte",
            "location__state": "AC",
            "location__coordinates__latitude": -24.7173085,
            "location__coordinates__longitude": -37.923167,
            "phone": ") 7871-6436",
            "picture__large": "http://martins.br/BrunoRodrigues/large.png",
            "picture__medium": "http://martins.br/BrunoRodrigues/medium.jpg",
            "picture__thumbnail": "http://martins.br/BrunoRodrigues/thumbnail.gif"
        },
        {
            "name__title": "mr",
            "name__first": "Leandro",
            "name__last": "Costela",
            "gender": "male",
            "location__street": "Alameda Luiz Felipe Sales, 698",
            "location__postcode": "15210-745",
            "location__city": "Martins",
            "location__state": "MT",
            "location__coordinates__latitude": -48.52416057042378,
            "location__coordinates__longitude": -21.76564042586542,
            "phone": "21 1901-3175",
            "picture__large": "https://da.com/LeandroCostela/large.png",
            "picture__medium": "https://da.com/LeandroCostela/medium.jpg",
            "picture__thumbnail": "https://da.com/LeandroCostela/thumbnail.gif"
        }
    ]
